### ISSUE TITLE
Mege Sort Implementation

### ISSUE THREAD

**Issue by ankithans** [Data-Science-Community-SRM/Algorithms-for-Programming#3]
# Merge Sort Implementation

## Prerequisites

- [x] Can you reproduce the problem in safe mode?
- [x] Are you running the latest version?
- [x] Did you check the debugging guide?
- [x] Did you check the FAQs on Discuss?
- [x] Are you reporting to the correct repository?
- [x] Did you perform a cursory search?

## Description

- implementation of merge sort

**Comment by ankithans** [comment]
can you assign this issue to me?

**Comment by cipheraxat** [comment]
You can take any topic any make a pull request for notes,basic question and hard ones , try the merge sort implemention questions and upload some notes too @ankithans !
